### ISSUE TITLE
Storing User Data in DynamoDB Question

### ISSUE THREAD

**Issue by vbuser2004** [jghaines/lambda-auth0-authorizer#3]
Great repo! I have a question about storing user information. In what situation would you want to use DynamoDb to store user data? Isn't it better to let Auth0 store this rather than duplicate it in your own table? Thank you!

**Comment by jghaines** [comment]
It depends on your preference. You can use the Auth0 APIs to store additional user information if you want.

The DynamoDB option gives you a bit more decoupling and allows you to store your user information in the AWS Region of your choice and with very low latency access.
